# Generated by Django 4.2.3 on 2023-07-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit_author', 'Create, update or delete authors'),)},
        ),
    ]
